// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int num = Integer.parseInt(args[0]);
		double above = 0, belowOrEqual = 0;
		for (int i = 0; i < num; i++) {
			double rnd = Math.random();
			if (rnd > 0.5) {
				above = above + 1;
			} else {
				belowOrEqual = belowOrEqual + 1;
			}
		}
		System.out.println("> 0.5: " + (int) above + " times");
		System.out.println("<= 0.5: " + (int) belowOrEqual + " times");
		if(Math.min(above, belowOrEqual) != 0)
		{
			double ratio = Math.min(above, belowOrEqual) / Math.max(above, belowOrEqual);
			System.out.println("Ratio " + ratio);
		}

	}
}
